[2023-02-22T20:23:30.658594+01:00] console.CRITICAL: Error thrown while running command ""make:migration"". Message: "There are no commands defined in the "make" namespace.  You may be looking for a command provided by the "MakerBundle" which is currently not installed. Try running "composer require symfony/maker-bundle --dev"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): There are no commands defined in the \"make\" namespace.\n\nYou may be looking for a command provided by the \"MakerBundle\" which is currently not installed. Try running \"composer require symfony/maker-bundle --dev\". at C:\\xampp\\htdocs\\Almacen\\Almacen\\vendor\\symfony\\framework-bundle\\EventListener\\SuggestMissingPackageSubscriber.php:73)","command":"\"make:migration\"","message":"There are no commands defined in the \"make\" namespace.\n\nYou may be looking for a command provided by the \"MakerBundle\" which is currently not installed. Try running \"composer require symfony/maker-bundle --dev\"."} []
[2023-02-22T20:23:32.881596+01:00] messenger.INFO: Sending message Symfony\Component\Mailer\Messenger\SendEmailMessage with async sender using Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport {"message":{"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage":[]},"class":"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage","alias":"async","sender":"Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineTransport"} []
[2023-02-22T20:29:33.230008+01:00] console.CRITICAL: Error thrown while running command ""make:migration"". Message: "There are no commands defined in the "make" namespace.  You may be looking for a command provided by the "MakerBundle" which is currently not installed. Try running "composer require symfony/maker-bundle --dev"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): There are no commands defined in the \"make\" namespace.\n\nYou may be looking for a command provided by the \"MakerBundle\" which is currently not installed. Try running \"composer require symfony/maker-bundle --dev\". at C:\\xampp\\htdocs\\Almacen\\Almacen\\vendor\\symfony\\framework-bundle\\EventListener\\SuggestMissingPackageSubscriber.php:73)","command":"\"make:migration\"","message":"There are no commands defined in the \"make\" namespace.\n\nYou may be looking for a command provided by the \"MakerBundle\" which is currently not installed. Try running \"composer require symfony/maker-bundle --dev\"."} []
[2023-02-22T20:29:33.308098+01:00] messenger.INFO: Sending message Symfony\Component\Mailer\Messenger\SendEmailMessage with async sender using Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport {"message":{"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage":[]},"class":"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage","alias":"async","sender":"Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineTransport"} []
[2023-02-22T20:30:22.988286+01:00] console.CRITICAL: Error thrown while running command ""make:migration"". Message: "There are no commands defined in the "make" namespace.  You may be looking for a command provided by the "MakerBundle" which is currently not installed. Try running "composer require symfony/maker-bundle --dev"." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): There are no commands defined in the \"make\" namespace.\n\nYou may be looking for a command provided by the \"MakerBundle\" which is currently not installed. Try running \"composer require symfony/maker-bundle --dev\". at C:\\xampp\\htdocs\\Almacen\\Almacen\\vendor\\symfony\\framework-bundle\\EventListener\\SuggestMissingPackageSubscriber.php:73)","command":"\"make:migration\"","message":"There are no commands defined in the \"make\" namespace.\n\nYou may be looking for a command provided by the \"MakerBundle\" which is currently not installed. Try running \"composer require symfony/maker-bundle --dev\"."} []
[2023-02-23T21:50:44.665334+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\DefaultController::login"},"request_uri":"https://localhost/tfg/almacen/public/index.php/iniciar-sesion","method":"POST"} []
[2023-02-23T21:50:44.680964+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2023-02-23T21:50:44.680973+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-02-23T21:50:44.753792+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES)" at C:\xampp\htdocs\tfg\almacen\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2023-02-23T21:50:44.833181+01:00] messenger.INFO: Sending message Symfony\Component\Mailer\Messenger\SendEmailMessage with async sender using Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport {"message":{"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage":[]},"class":"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage","alias":"async","sender":"Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineTransport"} []
[2023-02-23T21:51:59.323756+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\DefaultController::login"},"request_uri":"https://localhost/tfg/almacen/public/index.php/iniciar-sesion","method":"POST"} []
[2023-02-23T21:51:59.345692+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2023-02-23T21:51:59.345700+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-02-23T21:51:59.416334+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES)" at C:\xampp\htdocs\tfg\almacen\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2023-02-23T21:51:59.497368+01:00] messenger.INFO: Sending message Symfony\Component\Mailer\Messenger\SendEmailMessage with async sender using Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport {"message":{"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage":[]},"class":"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage","alias":"async","sender":"Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineTransport"} []
[2023-02-23T21:52:56.407567+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\DefaultController::login"},"request_uri":"https://localhost/tfg/almacen/public/index.php/iniciar-sesion","method":"POST"} []
[2023-02-23T21:52:56.426990+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2023-02-23T21:52:56.426998+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-02-23T21:52:56.476783+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES)" at C:\xampp\htdocs\tfg\almacen\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2023-02-23T21:53:16.312078+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\DefaultController::login"},"request_uri":"https://localhost/tfg/almacen/public/index.php/iniciar-sesion","method":"POST"} []
[2023-02-23T21:53:16.337437+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2023-02-23T21:53:16.337448+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-02-23T21:53:16.409177+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES)" at C:\xampp\htdocs\tfg\almacen\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2023-02-23T21:53:16.489070+01:00] messenger.INFO: Sending message Symfony\Component\Mailer\Messenger\SendEmailMessage with async sender using Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport {"message":{"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage":[]},"class":"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage","alias":"async","sender":"Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineTransport"} []
[2023-02-23T21:54:05.794311+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\DefaultController::login"},"request_uri":"https://localhost/tfg/almacen/public/index.php/iniciar-sesion","method":"POST"} []
[2023-02-23T21:54:05.812602+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2023-02-23T21:54:05.812611+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-02-23T21:54:05.875265+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES)" at C:\xampp\htdocs\tfg\almacen\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2023-02-23T21:54:29.360491+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\DefaultController::login"},"request_uri":"https://localhost/tfg/almacen/public/index.php/iniciar-sesion","method":"POST"} []
[2023-02-23T21:54:29.382093+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2023-02-23T21:54:29.382101+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-02-23T21:54:29.457715+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES)" at C:\xampp\htdocs\tfg\almacen\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2023-02-23T21:54:29.530451+01:00] messenger.INFO: Sending message Symfony\Component\Mailer\Messenger\SendEmailMessage with async sender using Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport {"message":{"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage":[]},"class":"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage","alias":"async","sender":"Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineTransport"} []
[2023-02-23T21:54:38.109230+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\DefaultController::login"},"request_uri":"https://localhost/tfg/almacen/public/index.php/iniciar-sesion","method":"POST"} []
[2023-02-23T21:54:38.126159+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2023-02-23T21:54:38.126167+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-02-23T21:54:38.175518+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES)" at C:\xampp\htdocs\tfg\almacen\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2023-02-23T21:56:53.439625+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\DefaultController::login"},"request_uri":"https://localhost/tfg/almacen/public/index.php/iniciar-sesion","method":"POST"} []
[2023-02-23T21:56:53.463394+01:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":1} []
[2023-02-23T21:56:53.463402+01:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2023-02-23T21:56:53.534679+01:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES)" at C:\xampp\htdocs\tfg\almacen\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDO\\Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'debianDB'@'localhost' (using password: YES) at C:\\xampp\\htdocs\\tfg\\almacen\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:40)"} []
[2023-02-23T21:56:53.612481+01:00] messenger.INFO: Sending message Symfony\Component\Mailer\Messenger\SendEmailMessage with async sender using Symfony\Component\Messenger\Bridge\Doctrine\Transport\DoctrineTransport {"message":{"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage":[]},"class":"Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage","alias":"async","sender":"Symfony\\Component\\Messenger\\Bridge\\Doctrine\\Transport\\DoctrineTransport"} []
